login: &login
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *login
  database: ghenio_development

test:
  <<: *login
  database: ghenio_test

production:
  <<: *login
  database: ghenio_development

staging:
  <<: *login
  database: ghenio_development